[features]
seeds = false
skip-lint = false
[programs.devnet]
swap = "6g7FMSAAjJK33JADSprJwaDwL5FPuyqRfqv6ekPKCdDz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/mnt/c/Users/detec/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/swap.ts"
